# Generated by Django 3.2.12 on 2025-09-22 00:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestao', '0003_auto_20250904_0041'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='presenca',
            name='presente',
        ),
        migrations.AddField(
            model_name='presenca',
            name='faltas',
            field=models.IntegerField(default=0),
        ),
    ]
