# Generated by Django 3.2.12 on 2025-09-24 21:03

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('gestao', '0004_auto_20250922_0001'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='turma',
            name='professor',
        ),
        migrations.AddField(
            model_name='turma',
            name='professor',
            field=models.ManyToManyField(related_name='turmas', to=settings.AUTH_USER_MODEL),
        ),
    ]
